### ISSUE TITLE
Create release with the latest changes over 2.0.0?

### ISSUE THREAD

**Issue by dsvgit** [w9jds/firebase-action#128]
Hello, @w9jds it seems like after the latest release https://github.com/w9jds/firebase-action/releases/tag/v2.0.0 the repo has some changes, can you create new one release, please? It would be convenient to put exact version into actions config `w9jds/firebase-action@v2.0.0` instead of using `master`.

**Comment by chen-eini-healthy** [comment]
@w9jds It would be great to have a new release

**Comment by w9jds** [comment]
Sadly, the way this action works, changing the version of the action won't accomplish anything. The way this publishes it will always pull the latest version of the image from docker hub. This was done because of complains when it did a full image creation for every run of the action. I can look into a process that deploys versioned images and maybe the action has to be updated to pull the versions of the image, but as it works now the action version doesn't change anything anymore.

**Comment by w9jds** [comment]
Moving forward all releases will now be versioned, and latest will pull the latest version pushed. On top of that master will now have it's own docker image so it is back to a proper release system. The new `v2.1.0` is now live. I also added support for github package as well so the image is available on Docker Hub and GitHub Packages

**Comment by chen-eini-healthy** [comment]
@w9jds Amazing! Thanks!
