### ISSUE TITLE
How to get deployed url from firebase and display it into pull request comment like netlfiy preview.

### ISSUE THREAD

**Issue by raviagheda** [w9jds/firebase-action#138]

**Comment by cgutierr-zgz** [comment]
@raviagheda did u managed to solve this?
I'd also like to post the url into the PR

Thanks!

**Comment by raviagheda** [comment]
Hi @cgutierr-zgz I've not yet.   
As team managed to get the URL from deploy build logs in the action log center. So it was scoped out from the blocker. 

But still curious to find out how we can make it work. :)

**Comment by w9jds** [comment]
I started working and released an early version of a replacement for this action here: https://github.com/w9jds/setup-firebase which should theoretically be MUCH easier to pull this information out of the execution. I had this in this action but it caused a lot of problems because of how shell handles it. (any kinds of errors prevented it from printing out logs, etc.)

I will hopefully be adding that functionality soonish
