### ISSUE TITLE
Latest Version does not have a Docker Image

### ISSUE THREAD

**Issue by bjclark13** [w9jds/firebase-action#224]
Hi, I had trouble running your action, it seems to be missing a docker image for the latest version

```
Pull down action image 'w9jds/firebase-action:v13.4.1'
Error: Docker pull failed with exit code 1
```

**Comment by sabirklm** [comment]
@bjclark13 This seems to be version conflicts. I was having same issue. I got this fixed with the following changes 
`  uses: w9jds/firebase-action@v12.9.0 `

**Comment by ir-fuel** [comment]
`13.4.0` works

**Comment by clintonb** [comment]
I have the same issue. This seems to happen with every release. Do you need some support on updating your release action @w9jds?

**Comment by w9jds** [comment]
I've tried fixing it multiple times. For some reason, even though I'm doing what GitHub documents list, when you automate creating a tag it doesn't trigger github actions properly (they say it's to prevent infinite loops, and you have to do a special key but it didn't work). So I have to manually delete the release and re-create to create it again each time.

**Comment by jserrano-alq** [comment]
We are having the same issue with 

`  
Error response from daemon: manifest for w9jds/firebase-action:v13.5.0 not found: manifest unknown: manifest unknown
`

**Comment by nisargraval13** [comment]
We are having an issue
`manifest for w9jds/firebase-action:v13.5.0 not found: manifest unknown: manifest unknown`

and when changed version then still
`Unable to resolve action w9jds/firebase-action@13.4.0, unable to find version 13.4.0`

**Comment by JavierPAYTEF** [comment]
Same issue here
 Error response from daemon: manifest for w9jds/firebase-action:v13.5.0 not found: manifest unknown: manifest unknown

Is there a way to evade this issue? I understand it's temporary issue when doing new deploys.
I'm currently using w9jds/firebase-action@master in my script, should I be using a specific version instead of @master?

**Comment by apinilabs-pascal** [comment]
> I've tried fixing it multiple times. For some reason, even though I'm doing what GitHub documents list, when you automate creating a tag it doesn't trigger github actions properly (they say it's to prevent infinite loops, and you have to do a special key but it didn't work). So I have to manually delete the release and re-create to create it again each time.

onTag is not triggered when tag is created by another pipeline since you can not trigger one pipeline from another. Just in case this may be the problem

**Comment by GonzoTheDev** [comment]
Maybe using a "@stable" version would be better for people whose github actions fail every time there is a new release. Does this exist for this package?

**Comment by e-simpson** [comment]
This seems to happen shortly after each version bump while the docker builds

**Comment by antoinealej** [comment]
Hey there! 
This happened again when the last commit has been pushed few hours ago: https://github.com/w9jds/firebase-action/commit/4ed8b16a90eb674b3cb98fc3ff62c838c43d2903
Version `13.6.1` doesn't exist in docker hub so our pipeline is now broken. https://hub.docker.com/r/w9jds/firebase-action/tags

**Comment by e-simpson** [comment]
This happens when the actions bot starts its automatic version bumping of the `firebase-tools` package. For a short period during build, the latest version is not ready yet and fails to pull. 

To get around this, instead of using `w9jds/firebase-action@master` (which will try to resolve a version number), pick a firebase-tools version you'd like to use and then supply it in the uses statement. For example (`v13.5.2`):

`uses: w9jds/firebase-action@v13.5.2`

You can find [firebase tools version codes here at npm](https://www.npmjs.com/package/firebase-tools?activeTab=versions).

**Comment by antoinealej** [comment]
Hi @e-simpson. Thanks you for the heads up. 
I bumped this just to give a general update, we did use a specific version to get around it while waiting for a proper fix.
Maybe like @GonzoTheDev proposed, a stable version would be a good idea.

**Comment by jasonrichdarmawan** [comment]
This has happened quite a number of time. Using a specific version is a no no bon bon. We set the CI/CD, we forget it, the next time, we will see @13 meanwhile the latest version is already at @20.
