### ISSUE TITLE
Equivalent of `firebase use <environment>`?

### ISSUE THREAD

**Issue by actuallymentor** [w9jds/firebase-action#36]
Thank you for creating this action.

How do I switch environments? The docs explain how to do it for hosting only (`args: deploy --only hosting:[environment name]`), but what if I want to run a wholesale deploy?

I'd like a equivalent to:

```
firebase use staging
firebase deloy
```

is this possible using this action and if so how?

**Comment by w9jds** [comment]
the `--only hosting:[environment name]` is using the system of `firebase use`. Firebase use just creates aliases in the firebase.json file. 

Those aliases are then used when you specify what you want.

```You can override what's being used as the currently active project by passing the --project flag with any CLI command. As an example: You can set your CLI to run against a Firebase project that you've assigned the staging alias. If you want to run a single command against the Firebase project that you've assigned the prod alias, then you can run, for example, firebase deploy --project=prod.```

Basically use just means you are setting it for all commands the the cli run instead of that single command.

**Comment by actuallymentor** [comment]
Thank you, works like a charm!
