### ISSUE TITLE
Workflow Failing

### ISSUE THREAD

**Issue by RafaelZasas** [w9jds/firebase-action#75]
I get an error saying `npm ERR! missing script: build-prod` 
It suggests this, `npm ERR! Did you mean this?
npm ERR!     build`

**Comment by RafaelZasas** [comment]
I managed to fix this by changing build-prod to build -- --prod

**Comment by RafaelZasas** [comment]
I ran `firebase use --add`  but I'm still getting this error: 

`Failed to get Firebase project <PROJECT-NAME> . Please make sure the project exists and your account has permission to access it.`

I'm an editor on the project and I'm able to deploy from the cmd using ng deploy.

**Comment by w9jds** [comment]
Missing script error is a standard npm error caused by the fact that it can't find that script you specified in the `project.json` file. This could mean either the script doesn't exist, or the project isn't setup properly in the container action for it to find the file. Your other error is pretty standard if it can't find the the `firebase.json` file, or your firebase token isn't valid for the project you are trying to deploy to.

This is an issue with how you have everything setup so more information will likely be needed if you want more help.

**Comment by RafaelZasas** [comment]
It was actually fixed by changing the line to deploy -- --prod but thank you!

**Comment by RafaelZasas** [comment]
I also had to add 

"esModuleInterop": true, "allowSyntheticDefaultImports": true

To the tsconfig and then ensure that the token was generated by the owner of the fb project and not me as an editor

**Comment by RafaelZasas** [comment]
Hi, was there an accepted fix for the problem I had other than the one I suggested?

**Comment by w9jds** [comment]
This isn't really a bug, the action basically dockerizes `firebase-tools` the parameters are all based on your current project configuration and deployment pipeline.

**Comment by deandreamatias** [comment]
I get the same message error and solved update my FIREBASE_TOKEN

> FIREBASE_TOKEN - Required if GCP_SA_KEY is not set. The token to use for authentication. This token can be aquired through the firebase login:ci command.
